# Generated by Django 4.2.11 on 2024-06-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setor',
            options={'managed': False},
        ),
    ]
