# Generated by Django 4.2.11 on 2024-06-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0002_alter_setor_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='setor',
            table='setor',
        ),
    ]
