# Generated by Django 4.2.11 on 2024-06-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nome_generico', models.CharField(blank=True, max_length=70, null=True)),
                ('nome_comercial', models.CharField(blank=True, max_length=50, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('preco_unit', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medicamentos',
                'managed': False,
            },
        ),
    ]
